# Generated by Django 3.1.2 on 2020-11-03 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_id', models.IntegerField()),
                ('comment', models.CharField(max_length=100)),
                ('goods', models.IntegerField(blank=True)),
                ('replies', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_title', models.CharField(max_length=100)),
                ('thread_desc', models.TextField(blank=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('tags', models.TextField(blank=True)),
            ],
        ),
    ]
