# Generated by Django 3.1.2 on 2020-11-03 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winning_app', '0004_auto_20201103_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='nick_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
