# Generated by Django 3.1.2 on 2020-11-03 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winning_app', '0005_comment_nick_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='nick_name',
            field=models.CharField(default='匿名さん', max_length=20, null=True),
        ),
    ]
