# Generated by Django 3.1.2 on 2020-11-08 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winning_app', '0007_thread_comment_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='comment_number',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
